// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillMa.EntityFramework;

#nullable disable

namespace SkillMer.Server.Migrations
{
    [DbContext(typeof(SkillMerDbContext))]
    [Migration("20220810130756_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("SkillMer.Shared.Entities.MJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MUserUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TUsersJobJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TUsersJobUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("MUserUserId");

                    b.HasIndex("TUsersJobUserId", "TUsersJobJobId");

                    b.ToTable("m_job", (string)null);
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.MSkill", b =>
                {
                    b.Property<string>("SkillId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MUserUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TUsersSkillSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TUsersSkillUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("SkillId");

                    b.HasIndex("MUserUserId");

                    b.HasIndex("TUsersSkillUserId", "TUsersSkillSkillId");

                    b.ToTable("m_skill", (string)null);
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.MUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TUsersJobJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TUsersJobUserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TUsersSkillSkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TUsersSkillUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("TUsersJobUserId", "TUsersJobJobId");

                    b.HasIndex("TUsersSkillUserId", "TUsersSkillSkillId");

                    b.ToTable("m_user", (string)null);
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.TUsersJob", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "JobId");

                    b.ToTable("t_usersJob", (string)null);
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.TUsersSkill", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteFlg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SkillId");

                    b.ToTable("t_usersSkill", (string)null);
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.MJob", b =>
                {
                    b.HasOne("SkillMer.Shared.Entities.MUser", null)
                        .WithMany("Jobs")
                        .HasForeignKey("MUserUserId");

                    b.HasOne("SkillMer.Shared.Entities.TUsersJob", null)
                        .WithMany("Jobs")
                        .HasForeignKey("TUsersJobUserId", "TUsersJobJobId");
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.MSkill", b =>
                {
                    b.HasOne("SkillMer.Shared.Entities.MUser", null)
                        .WithMany("Skills")
                        .HasForeignKey("MUserUserId");

                    b.HasOne("SkillMer.Shared.Entities.TUsersSkill", null)
                        .WithMany("Skills")
                        .HasForeignKey("TUsersSkillUserId", "TUsersSkillSkillId");
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.MUser", b =>
                {
                    b.HasOne("SkillMer.Shared.Entities.TUsersJob", null)
                        .WithMany("Users")
                        .HasForeignKey("TUsersJobUserId", "TUsersJobJobId");

                    b.HasOne("SkillMer.Shared.Entities.TUsersSkill", null)
                        .WithMany("Users")
                        .HasForeignKey("TUsersSkillUserId", "TUsersSkillSkillId");
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.MUser", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.TUsersJob", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SkillMer.Shared.Entities.TUsersSkill", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
